// Rebuild the supplementary source-message catalog without a runtime dependency.
import {readFile,writeFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url),langs=['fr','en','de','es','pt'];
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/œ/g,'oe').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
const encode=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const ui=await import(encode(await readFile(new URL('i18n.js',root),'utf8')+'\nexport {UI_STRINGS};'));
const wsSource=await readFile(new URL('workspace.js',root),'utf8');
const ws=await import(encode(wsSource.slice(wsSource.indexOf('const COPY'),wsSource.indexOf('export function workspaceText'))+'\nexport {COPY};'));
const messages={};
function add(source,translations){if(typeof source==='string'&&langs.every(l=>typeof translations[l]==='string'))messages[normalize(source)]=translations;}
function walk(value,path=[]){for(const [k,v]of Object.entries(value)){const keys=[...path,k];if(typeof v==='string'){const translations=Object.fromEntries(langs.map(l=>[l,keys.reduce((a,p)=>a?.[p],ui.UI_STRINGS[l])]));add(v,translations);if(translations.en)add(translations.en,translations);}else if(v&&typeof v==='object')walk(v,keys);}}
walk(ui.UI_STRINGS.fr);
for(const key of Object.keys(ws.COPY.fr)){const row=Object.fromEntries(langs.map(l=>[l,ws.COPY[l][key]]));add(row.fr,row);add(row.en,row);}
const rows=(await readFile(new URL('locales/additional.tsv',root),'utf8')).split('\n');
for(const line of rows){if(!line.trim()||line.startsWith('#'))continue;const values=line.split('|').map(value=>value.replace(/\\n/g,'\n'));if(values.length!==5)throw Error('Expected five languages: '+line);const row=Object.fromEntries(langs.map((l,i)=>[l,values[i]]));add(row.fr,row);}
await writeFile(new URL('locales/messages.js',root),'// Generated by node scripts/build-locales.mjs. Edit locales/additional.tsv or the existing catalogs.\nexport const MESSAGES = '+JSON.stringify(messages,null,2)+';\n');
console.log(`${Object.keys(messages).length} messages, all five languages present.`);
